---
name: CI
on:
  pull_request:
    branches:
      - main
      - master
      - beta
  push:
    branches:
      - main
      - master
      - beta
permissions:
  contents: write
  issues: write
  pull-requests: write
  id-token: write

jobs:
  ci:
    uses: Neovici/cfg/.github/workflows/foundry.yml@master
    secrets: inherit